behaviors:
  SimpleAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 0.0003
      learning_rate_schedule: linear
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    checkpoint_interval: 5000
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 5000
    time_horizon: 64
    summary_freq: 200
env_settings:
  env_path: "/Users/victorbarbosa/git/UNITY Web/SimpleTrain/Mac/App.app"
  base_port: 5005
  num_envs: 2
  num_areas: 1
  timeout_wait: 60
  seed: 42
engine_settings:
  width: 84
  height: 84
  quality_level: 0
  time_scale: 50.0
  target_frame_rate: -1
  no_graphics: true
environment_parameters:
  currentLesson: 1
  maxHorizonatal: 2
  steps: 1
checkpoint_settings:
  run_id: test_multi
  results_dir: results
torch_settings:
  device: cpu
debug: true
