#!/usr/bin/env python3
"""
Test script to decode side_channel data generated by Rust
"""

import struct
import uuid

def decode_side_channel(data: bytes):
    """Decode side channel data in the format our Rust code generates"""
    print(f"Total data length: {len(data)} bytes")
    print(f"Data (hex): {data.hex()}\n")
    
    offset = 0
    message_count = 0
    
    while offset < len(data):
        message_count += 1
        print(f"=== Message #{message_count} ===")
        
        # Read UUID (16 bytes, little-endian)
        if offset + 16 > len(data):
            print(f"ERROR: Not enough bytes for UUID at offset {offset}")
            break
            
        uuid_bytes = data[offset:offset+16]
        channel_uuid = uuid.UUID(bytes_le=uuid_bytes)
        print(f"Channel UUID: {channel_uuid}")
        offset += 16
        
        # Read message length (4 bytes, i32, little-endian)
        if offset + 4 > len(data):
            print(f"ERROR: Not enough bytes for length at offset {offset}")
            break
            
        msg_len = struct.unpack('<i', data[offset:offset+4])[0]
        print(f"Message length: {msg_len} bytes")
        offset += 4
        
        # Read message data
        if offset + msg_len > len(data):
            print(f"ERROR: Not enough bytes for message body at offset {offset}")
            break
            
        msg_data = data[offset:offset+msg_len]
        offset += msg_len
        
        # Decode message body
        msg_offset = 0
        
        # Read key string
        key_len = struct.unpack('<i', msg_data[msg_offset:msg_offset+4])[0]
        msg_offset += 4
        key = msg_data[msg_offset:msg_offset+key_len].decode('ascii')
        msg_offset += key_len
        print(f"  Key: '{key}'")
        
        # Read data type
        data_type = struct.unpack('<i', msg_data[msg_offset:msg_offset+4])[0]
        msg_offset += 4
        print(f"  Data type: {data_type} {'(FLOAT)' if data_type == 0 else '(SAMPLER)'}")
        
        # Read float value
        if data_type == 0:
            value = struct.unpack('<f', msg_data[msg_offset:msg_offset+4])[0]
            msg_offset += 4
            print(f"  Value: {value}")
        
        print()

if __name__ == "__main__":
    # Test with some sample data (we'll get real data from Rust)
    print("Side Channel Decoder Test\n")
    print("Waiting for hex dump from Rust program...")
    print("Copy the hex bytes and paste here (or modify script to read from file)\n")
    
    # Expected UUID
    expected_uuid = uuid.UUID("534c891e-810f-11ea-a9d0-822485860400")
    print(f"Expected UUID: {expected_uuid}")
    print(f"Expected UUID (bytes_le): {expected_uuid.bytes_le.hex()}\n")
